# yaml-language-server: https://squidfunk.github.io/mkdocs-material

# Project information
site_name: My Dev Notes

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Additional configuration
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ozlmulg
      name: GitHub
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/ozlmulg
      name: Docker Hub
    - icon: material/copyright
      link: https://squidfunk.github.io/mkdocs-material/
      name: Mkdocs Material

# Page tree
nav:
  - Home: index.md
  - Linux:
      - Linux Cheatsheet: linux/linux-cheatsheet.md
      - Linux Network Cheatsheet: linux/linux-network-cheatsheet.md
  - Git:
      - Git Cheatsheet: git/git-cheatsheet.md
      - GitHub Actions: git/github-actions.md
      - Tmate: git/tmate.md
      - List GitHub Actions: git/list-github-actions.md
  - Maven:
      - Maven Wrapper: maven/maven-wrapper.md
  - Java:
      - Jenv: java/jenv.md
  - Docker:
      - Docker Cheatsheet: docker/docker-cheatsheet.md
      - Docker Compose Cheatsheet: docker/docker-compose-cheatsheet.md
      - Docker Examples: docker/docker-examples.md
  - Kubernetes:
      - Minikube: kubernetes/minikube.md
      - Kubectl: kubernetes/kubectl.md
      - Kubeadm: kubernetes/kubeadm.md
  - Terraform:
      - Terraform Cheatsheet: terraform/terraform-cheatsheet.md
      - Tfenv: terraform/tfenv.md
  - Node.js:
      - Nvm & Npm: nodejs/nvm-npm.md
  - Database:
      - MySQL:
          - MySQL Cheatsheet: database/mysql/mysql-cheatsheet.md
      - PostgreSQL:
          - PostgreSQL Cheatsheet: database/postgresql/postgresql-cheatsheet.md
          - PostgreSQL JSONB Operations: database/postgresql/postgresql-jsonb-operations.md
  - Mobile:
      - Android:
          - Android Firebase Integration: mobile/android/android-firebase-integration.md
          - Android Keystore Settings: mobile/android/android-keystore-settings.md
          - Android Google Maps Integration: mobile/android/android-google-maps-integration.md
          - Android Push Notification Integration: mobile/android/android-push-notification-integration.md
      - iOS:
          - iOS Firebase Integration: mobile/ios/ios-firebase-integration.md
          - iOS Google Maps Integration: mobile/ios/ios-google-maps-integration.md
          - iOS Test Flight Integration: mobile/ios/ios-test-flight-integration.md
          - iOS Push Notification Integration: mobile/ios/ios-push-notification-integration.md
  - Slack:
      - Slack Reminder: slack/slack-reminder.md
      - Slack Message: slack/slack-message.md
      - Slack User Group Creation: slack/slack-user-group-creation.md
      - Slack GitHub Workflows: slack/slack-github-workflows.md
  - Tools:
      - Apicurio via Docker: tools/apicurio-via-docker.md
      - KafkaUI via Docker: tools/kafkaui-via-docker.md
      - Multi-Gitter: tools/multi-gitter.md